			<header class="clearfix">
			<h1><a href="../"><img src="../img/logo_career_plus.jpg" alt="キャリアプラス"></a></h1><p class="sub_t">コールセンター派遣ならキャリアプラス！</p>
			<ul class="h_right">
				<li><a href="../privacy/index.php">プライバシーポリシー</a></li>
				<li><a href="../koukai_cap_201409.pdf" target="_blank">労働者派遣事業に関する情報公開について</a></li>
				<li><a href="../kyouiku_kunren/" target="_blank">教育訓練計画について</a></li>
			</ul>
			</header>
			<nav>
				<ul class="navi clearfix">
					<li class="sp_set"><a href="../">トップ</a></li>
					<li class="sp_set"><a href="http://www.career-plus.co.jp/company/index.php">会社概要</a></li>
					<li class="sp_set"><a href="http://www.career-plus.co.jp/company/voice.php">代表挨拶</a></li>
					<li class="sp_set"><a target="_blank" href="https://www.s-mypage.com/mypage/cap">スタッフ専用<br />マイページへ</a></li>
					<li class="sp_set"><a target="_blank" href="http://www.hibarai.com/index.cfm?fuseaction=job.joblist&sfw=csa">札幌の<br />お仕事情報</a></li>
					<li class="sp_set"><a target="_blank" href="http://www.hibarai.com/index.cfm?fuseaction=job.joblist&sfw=csh">新宿の<br />お仕事情報</a></li>
					<li class="sp_set"><a target="_blank" href="https://www.hibarai.com/index.cfm?fuseaction=job.joblist&sno=&sar=9&sfw=%E3%82%AD%E3%83%A3%E3%83%AA%E3%82%A2%E3%83%97%E3%83%A9%E3%82%B9">福岡の<br />お仕事情報</a></li>
					<li><a target="_blank" href="http://www.hibarai.com/index.cfm?fuseaction=job.joblist&sfw=cok">沖縄の<br />お仕事情報</a></li>
				</ul>
			</nav>
